# Generated by Django 3.2 on 2023-06-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_organisation_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'default_related_name': 'organisations'},
        ),
    ]
